//
// Created by Miquel Àngel Soler on 8/11/15.
//

#ifndef PMCONCERTPARAULES_PMAUDIOANALYZERCONSTANTS_H
#define PMCONCERTPARAULES_PMAUDIOANALYZERCONSTANTS_H

// Pitch
static const float PITCH_MINFREQ = 100.0f;
static const float PITCH_MAXFREQ = 800.0f;


#endif //PMCONCERTPARAULES_PMAUDIOANALYZERCONSTANTS_H
